### ISSUE TITLE
Interactive mode exception handling issues / bugs

### ISSUE THREAD

**Issue by 7a** [owtf/http-request-translator#47]
It looks like when using interactive mode like this:
http_request_translator --interactive

When unexpected Control + D sequences are used, the following happens, would be more professional to handle this in a more graceful way :)

Steps:
1) Paste a request + convert it
2) Paste another request, play with Control + D at the wrong time
3) The following happens:

```
>>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> >>> 
>>> Traceback (most recent call last):
  File "/usr/local/bin/http_request_translator", line 4, in <module>
    __import__('pkg_resources').run_script('http-request-translator==0.1', 'http_request_translator')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 54, in <module>

  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 49, in take_arguments

  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 34, in process_arguments
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 100, in take_headers
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 131, in take_body
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 100, in take_headers
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 122, in take_body
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 170, in parse_raw_request
UnboundLocalError: local variable 'host' referenced before assignment
```

**Comment by dhruvagarwal** [comment]
@7a cannot reproduce this error :disappointed: . Can you be more explicit ?

**Comment by 7a** [comment]
Step 1) Run:

```
http_request_translator --interactive
```

Step 2) type whatever: "mec"

```
Enter request headers (Ctrl+D to finish/Ctrl+C to quit).
>>> mec
```

Step 3) Control + D

```
>>> 
Enter request body/parameters (Ctrl+D to finish/Ctrl+C to quit).
```

Step 4) Control + D

```
>>> Traceback (most recent call last):
  File "/usr/local/bin/http_request_translator", line 4, in <module>
    __import__('pkg_resources').run_script('http-request-translator==0.1', 'http_request_translator')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 54, in <module>

  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 49, in take_arguments

  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 34, in process_arguments
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 100, in take_headers
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 122, in take_body
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 170, in parse_raw_request
UnboundLocalError: local variable 'host' referenced before assignment
```

**Comment by 7a** [comment]
Even easier, just use that request and "Control +D" :P

```
$ http_request_translator --interactive
Enter request headers (Ctrl+D to finish/Ctrl+C to quit).
>>> GET https://target.com/path/to/target HTTP/1.1
Connection: keep-alive
Content-Length: 0
>>> >>> >>> 
>>> 
Enter request body/parameters (Ctrl+D to finish/Ctrl+C to quit).
>>> Traceback (most recent call last):
  File "/usr/local/bin/http_request_translator", line 4, in <module>
    __import__('pkg_resources').run_script('http-request-translator==0.1', 'http_request_translator')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 54, in <module>

  File "/usr/local/lib/python2.7/dist-packages/http_request_translator-0.1-py2.7.egg/EGG-INFO/scripts/http_request_translator", line 49, in take_arguments

  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 34, in process_arguments
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 100, in take_headers
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 122, in take_body
  File "build/bdist.linux-i686/egg/http_request_translator/translator.py", line 170, in parse_raw_request
UnboundLocalError: local variable 'host' referenced before assignment
```
