### ISSUE TITLE
Error on submitting HTTP request for 9gag.com

### ISSUE THREAD

**Issue by saganshul** [owtf/http-request-translator#59]
## Description
Error on submitting HTTP request for 9gag.com

**HTTP Request**
GET / HTTP/1.1
Host: 9gag.com
Connection: keep-alive

I think blindly trusting https://gist.github.com/mnordhoff/2213179 was not a good idea.
Error can be found in hrt/util.py

[9gag.com](http://9gag.com ) which is correct domain failing to satisfy written regex.

**Comment by viyatb** [comment]
@saganshul There must be some traceback from the tool. Can you paste it?

**Comment by saganshul** [comment]
Traceback (most recent call last):
  File "/home/singhal/hrt/bin/hrt", line 4, in <module>
    __import__('pkg_resources').run_script('hrt==0.1', 'hrt')
  File "/home/singhal/hrt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/singhal/hrt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/home/singhal/hrt/local/lib/python2.7/site-packages/hrt-0.1-py2.7.egg/EGG-INFO/scripts/hrt", line 6, in <module>
    
  File "build/bdist.linux-x86_64/egg/hrt/cli.py", line 13, in init
  File "build/bdist.linux-x86_64/egg/hrt/interface.py", line 60, in generate_code
  File "build/bdist.linux-x86_64/egg/hrt/plugin_manager.py", line 37, in generate_script
  File "build/bdist.linux-x86_64/egg/hrt/base.py", line 46, in __init__
  File "build/bdist.linux-x86_64/egg/hrt/base.py", line 175, in create_url
ValueError: Invalid URL 'http://9gag.com/'.

**Comment by DePierre** [comment]
@saganshul Thanks for reporting the issue. 

> I think blindly trusting https://gist.github.com/mnordhoff/2213179 was not a good idea.

The issue is not coming from that gist but from the custom regex written back in the very beginning of the project (see https://github.com/owtf/http-request-translator/blob/478ccdaa966d381aedac959224acff2c15ffb231/http_request_translator/pythonScripts.py#L26).

Currently testing fix.

**Comment by DePierre** [comment]
The bug was due to the improper regex in `util.py` where a domain containing digits would not match.

Now:
```bash
$ hrt -r "GET / HTTP/1.1
Host: 9gag.com
Connection: keep-alive"
#!/usr/bin/env bash
curl -v --request GET http://9gag.com/  --header "Host: 9gag.com"  --header "Connection: keep-alive"  --include
```
